/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    HFooter: typeof import('./src/components/HFooter.vue')['default']
    HHeader: typeof import('./src/components/HHeader.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    ParkingInfo: typeof import('./src/pages/ParkingInfo.vue')['default']
    ParkingInfoItem: typeof import('./src/components/ParkingInfoItem.vue')['default']
    ParkingLot: typeof import('./src/pages/ParkingLot.vue')['default']
    ParkingLotItem: typeof import('./src/components/ParkingLotItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
