/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    HFooter: typeof import('./src/components/HFooter.vue')['default']
    HHeader: typeof import('./src/components/HHeader.vue')['default']
    Home: typeof import('./src/pages/Home.vue')['default']
    ParkingInfo: typeof import('./src/pages/ParkingInfo.vue')['default']
    ParkingInfoItem: typeof import('./src/components/ParkingInfoItem.vue')['default']
    ParkingLot: typeof import('./src/pages/ParkingLot.vue')['default']
    ParkingLotItem: typeof import('./src/components/ParkingLotItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
